name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: docker pull kaushalkhonde2107/github-actions:latest
    - name: Delete Old docker container
      run: docker rm -f kaushal-github-actions || true
    - name: Run Docker Container
      run: docker run -d -p 8099:8000 --name kaushal-github-actions kaushalkhonde2107/github-actions
    
