name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull kaushalkhonde2107/github-actions:latest
    - name: Delete Old docker container
      run: sudo docker rm -f github-actions || true
    - name: Run Docker Container
      run: sudo docker run -d -p 80:8080 --name kaushal-github-actions kaushalkhonde2107/github-actions
