name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker Image
        run: docker build -t your_username/your_image_name:latest .

      - name: Push the Docker Image
        run: docker push your_username/your_image_name:latest

  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH key
        uses: shimatsu/setup-ssh-key@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        uses: actions/ssh@v3
        with:
          host: your_ec2_public_ip
          username: your_ec2_username
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull your_username/your_image_name:latest
            docker stop your_existing_container
            docker rm your_existing_container
            docker run -d -p 80:80 your_username/your_image_name:latest
